# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2ppx3QuZLpvk9zoO84fzrwsQLhKz2n4
"""

#Installing Kaggle
!pip install kaggle

# configuring the path of Kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""# **Importing Kaggle Earthquake dataset**"""

#Api from kaggle dataset
!kaggle competitions download -c LANL-Earthquake-Prediction

# extracting the compessed Dataset
from zipfile import ZipFile
dataset = '/content/LANL-Earthquake-Prediction.zip'
with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

import pandas as pd
pd.read_csv('/content/train.csv')

