# -*- coding: utf-8 -*-
"""Data Standardization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7_qtJg-NrSN6YQ_6ZYx1WgkYpYXJazZ
"""

#Importing

import pandas as pd
import numpy as np
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Loading the dataset
dataset=sklearn.datasets.load_breast_cancer()

#Loading to pandas
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

df.head()

df.shape

x= df
y=dataset.target

print(x)

print(y)

"""# **Splitting Data into training and test **"""

x_train , x_test , y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=3)

print(x.shape, x_train.shape,x_test.shape)

"""# **Finding Standard Deviation**"""

print(dataset.data.std())

"""# **Standardization**"""

# Taking Scaler
scaler= StandardScaler()

# Standardizing
scaler.fit(x_train)

#Trnsforming
x_train_standardized= scaler.transform(x_train)

x_train_standardized

# Standardizing X_test based on x_train
x_test_standardized= scaler.transform(x_test)

x_test_standardized

#Checking Standard Deviation
print(x_train_standardized.std())
print(x_test_standardized.std())

