# -*- coding: utf-8 -*-
"""Experta .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3_OksxLtVW8r9f7LAqpCVMgsxlw8kFD
"""

pip install --upgrade experta

pip install experta

from random import choice
from experta import *


class Light(Fact):
    """Info about the traffic light."""
    pass


class RobotCrossStreet(KnowledgeEngine):
    @Rule(Light(color='green'))
    def green_light(self):
        print("Walk")

    @Rule(Light(color='red'))
    def red_light(self):
        print("Don't walk")

    @Rule(AS.light << Light(color=L('yellow') | L('blinking-yellow')))
    def cautious(self, light):
        print("Be cautious because light is", light["color"])

""">>> engine = RobotCrossStreet()

>>> engine.reset()

>>> engine.declare(Light(color=choice(['green', 'yellow', 'blinking-yellow', 'red'])))

>>> engine.run()

Be cautious because light is blinking-yellow

"""