# -*- coding: utf-8 -*-
"""Handle Missing Values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GlY-dGeL1HbmH2tIHOT_xdkEu-1iH9-X
"""

#How to handle  missing Values
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Loading the datasets
datasets= pd.read_csv('/content/Placement_Dataset.csv')
datasets.head()

datasets.shape

"""# **Finding Missing Values**"""

datasets.isnull().sum()

sns.displot(datasets.salary)

"""# **Filling With Median Values**"""

datasets['salary'].fillna(datasets['salary'].median(), inplace=True)

datasets.isnull().sum()

"""# **Filling with Mean**"""

datasets['salary'].fillna(datasets['salary'].mean(), inplace=True)

datasets.isnull().sum()

"""# **Mode**"""

datasets['salary'].fillna(datasets['salary'].mode(), inplace=True)

datasets.isnull().sum()

"""# **Dropping**"""

#Loading the datasets
datasets2= pd.read_csv('/content/Placement_Dataset.csv')
datasets2.head()

datasets2.isnull().sum()

#Drop
datasets2=datasets2.dropna(how='any')

datasets2.isnull().sum()

datasets2.shape

