# -*- coding: utf-8 -*-
"""OpenCV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jpZwoVPA4iS4MCyGZvbgC2QtOqdSa9Ny

## **IMPORT**
"""

pip install opencv-python

"""# Open a connection to the default camera (camera index 0)

"""

import cv2

# Open a connection to the default camera (camera index 0)
cap = cv2.VideoCapture(0)

"""# Check if the camera opened successfully

"""

if not cap.isOpened():
    print("Error: Could not open camera.")
    exit()

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # If the frame is read correctly, ret is True
    if not ret:
        print("Error: Couldn't read frame.")
        break

    # Display the resulting frame
    cv2.imshow("Video", frame)

    # Break the loop if 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the camera and close all windows
cap.release()
cv2.destroyAllWindows()

