# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SCzWSGdgWlhtGZ6WvyDA9Bll09NoJWrB

### ***Pandas***
"""

import pandas as pd

data=pd.read_csv('/content/sample_data/california_housing_test.csv')
print(data)

type(data)

data.head()

data.to_csv('data.csv')

import numpy as np
dd= pd.DataFrame(np.random.rand(4,4))
dd.head()

type(dd)

dd

dd.head()

dd.tail()

dd.info

data.info

"""## PROPER IMPORT FROM **SKLEARN**"""

from sklearn import datasets
data=datasets.load_diabetes()
type(data)

print(data.keys())

df = pd.DataFrame(data.data, columns=data.feature_names)
df.head()

df.value_counts('s6')

df.groupby('s6').mean()

dd.mean()

