# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQwVkNVSPFQGhUj1hzjbObJ85FoHgj3l
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#Datasets
tips= sns.load_dataset('tips')
tips.head()

"""# **Setting Theme**

"""

#Setting Theme
sns.set_theme()

"""# **Visualising**"""

sns.relplot(data=tips, x='total_bill',y='tip', col='time',hue='smoker',style='smoker',size='size')

"""# **Iris Datasets**"""

iris= sns.load_dataset('iris')

iris.head()

#Scatter Plot
sns.scatterplot(data=iris, x='sepal_length',y='petal_length', hue='species')

"""# **Titanic Data**"""

#Importing
titanic = sns.load_dataset('titanic')

titanic.head()

sns.scatterplot(data=titanic, x='class', y='alone', hue='survived')

"""# **CountPlot**"""

sns.countplot(x='class', data= titanic)

# How many have survived

sns.countplot(x="survived", data= titanic)

"""# **Barchart**"""

sns.barplot(x='sex',y='survived', hue='class', data= titanic)

