# -*- coding: utf-8 -*-
"""Sympy .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WmRF6cggTFKjiedNWAbUKJqwDk91Gb_0

# **IMPORT**
"""

from sympy import symbols, sin
from sympy.plotting import plot

"""# **plot**"""

x = symbols('x')
plot(sin(x), (x, -3.14, 3.14))