# -*- coding: utf-8 -*-
"""System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13s6338K-4HAd_S_C2xeuP6gS74Xl_nDN

Trying hands
"""

print("hello")

! cat /proc/cpuinfo

! cat /proc/meminfo



"""# **numPy**"""

import numpy as np
from time import process_time
start_time1=process_time()
k=[i+5 for i in range(10000)]
l=[i+5 for i in k]
end_time1=process_time()
print(end_time1-start_time1)

start_time2=process_time()
n=np.array([i for i in range(10000)])
n+=5
end_time2=process_time()
print(end_time2-start_time2)



from google.colab import drive
drive.mount('/content/drive')