# -*- coding: utf-8 -*-
"""TrainTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1592brPQ8q90tCC891NHo7kzedrky4dbD

# **IMPORT**
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

"""# **Datasets Import**"""

data=pd.read_csv("/content/diabetes.csv")

data.head()

data['Outcome'].value_counts()

"""# **Separating Features and Target**"""

x= data.drop(columns='Outcome',axis=1)
y=data['Outcome']

"""# **Standardization**"""

scaler= StandardScaler()

"""# **Standardizing X(features)**"""

scaler.fit(x)

std_data=scaler.transform(x)

print(std_data)

X=std_data
Y=data['Outcome']

print(X)
print(Y)

"""# **SPlITTING**"""

X_train, X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape, Y.shape,X_train.shape,X_test.shape,y_train.shape,y_test.shape)

