# -*- coding: utf-8 -*-
"""Vector Operations 2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B83O9J7rOY973SNiRegAHEOqaYR1vH0W

# **IMPORT**
"""

import numpy as np
import pandas as pd

a= np.array([2,3])
b= np.array([4,4])
a_dot_b=np.dot(a,b)
print(a_dot_b)

c= np.array([2,3,4])
d= np.array([4,4,6])
c_dot_d=np.dot(c,d)
print(c_dot_d)

"""# **Cross Product**"""

a= np.array([2,3])
b= np.array([4,4])
a_cross_b=np.cross(a,b)
print(a_cross_b)

a= np.array([2,3,6])
b= np.array([4,4,7])
a_cross_b=np.cross(a,b)
print(a_cross_b)

"""# **Projection**

formula           
 proj a= ((a.v)/v_magnitude**2) *v
"""

a= np.array([2,5])
b= np.array([8,-6])
mag_b=np.sqrt(sum(b**2))**2
proj_a_on_b= (np.dot(a,b)/mag_b)*b
print(proj_a_on_b)

a= np.array([2,5,5])
b= np.array([8,-6,8])
mag_b=np.sqrt(sum(b**2))**2
proj_a_on_b= (np.dot(a,b)/mag_b)*b
print(proj_a_on_b)

