# -*- coding: utf-8 -*-
"""Vectors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbfsRuyr-x24LIafJ-G2Cc1HZod5h4zu

# **IMPORT**
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

"""# **Plotting a vector**"""

plt.quiver(0,0,4,5,scale_units='xy', angles='xy', scale=1, color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

"""# **Addition of 2 Vectors**"""

v1=np.asarray([0,0,2,3])
v2=np.asarray([0,0,3,-2])
print(v1+v2)

"""# **Subtraction of vectors**"""

v1=np.asarray([0,0,2,3])
v2=np.asarray([0,0,3,-2])
print(v1-v2)

plt.quiver(0,0,2,3,scale_units='xy', angles='xy', scale=1, color='r')
plt.quiver(0,0,3,-2,scale_units='xy', angles='xy', scale=1, color='g')
plt.quiver(0,0,5,1,scale_units='xy', angles='xy', scale=1, color='b')
plt.quiver(0,0,-1,5,scale_units='xy', angles='xy', scale=1, color='y')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

"""# **Multiplying Vector By Scalar**"""

v1=np.asarray([0,0,2,3])
print(2*v1)

plt.quiver(0,0,2,3,scale_units='xy', angles='xy', scale=1, color='r')
plt.quiver(0,0,4,6,scale_units='xy', angles='xy', scale=1, color='g')

plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

