# -*- coding: utf-8 -*-
"""Wishper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mN-CdWHkPD5DOzOOj1xzMjo47csr_k82
"""

!pip install git+https://github.com/openai/whisper.git
 !sudo apt update && sudo apt install ffmpeg

!whisper "/content/Types of Relationships In India _ Indian Relationships.mp3" --model medium.en

